#!/usr/bin/env node
import http from 'node:http'; import crypto from 'node:crypto'; import fs from 'node:fs'; import path from 'node:path'; import os from 'node:os'; import net from 'node:net'; import {fileURLToPath} from 'node:url';
const HERE=path.dirname(fileURLToPath(import.meta.url)), ROOT=path.resolve(HERE,'../..');
const STATE=process.env.SPIKE_BRIDGE_MAC_STATE_DIR||process.env.SPIKE_WORKER_B_STATE_DIR||path.join(ROOT,'state','agents','mac'), REVERSE=path.join(STATE,'reverse'), CALL_CARDS=path.join(STATE,'call-cards');
const DIRS=Object.fromEntries(['queued','processing','results','status'].map(n=>[n,path.join(REVERSE,n)])); const REGISTRATION=path.join(STATE,'registration.json');
const PORT=Number(process.env.SPIKE_WORKER_B_PORT||8766), DEFAULT_MAC_PORT=Number(process.env.SPIKE_WORKER_B_MAC_PORT||8767), REGISTRATION_MAX_AGE_MS=90*1000, MAX_BODY=128*1024, MAX_RESULT_BODY=128*1024, ID_RE=/^[A-Za-z0-9][A-Za-z0-9._-]{0,95}$/;
for(const d of Object.values(DIRS))fs.mkdirSync(d,{recursive:true}); const stateSecretPath=path.join(STATE,'pairing.secret'), canonicalSecretPath=path.join(ROOT,'secrets','mac','pairing.secret'); const explicitState=Boolean(process.env.SPIKE_BRIDGE_MAC_STATE_DIR||process.env.SPIKE_WORKER_B_STATE_DIR); const secretPath=process.env.SPIKE_BRIDGE_MAC_SECRET_FILE||(explicitState&&fs.existsSync(stateSecretPath)?stateSecretPath:canonicalSecretPath); fs.mkdirSync(path.dirname(secretPath),{recursive:true}); const secret=fs.existsSync(secretPath)?fs.readFileSync(secretPath,'utf8').trim():crypto.randomBytes(32).toString('hex'); if(!fs.existsSync(secretPath))fs.writeFileSync(secretPath,secret+'\n',{mode:0o600});
fs.mkdirSync(CALL_CARDS,{recursive:true});
const taskBearer=crypto.createHmac('sha256',secret).update('task-api-v1').digest('hex'), bootstrapToken=crypto.randomBytes(24).toString('hex'), pairToken=crypto.randomBytes(24).toString('hex');
const template=fs.readFileSync(path.join(HERE,'mac-worker-b-bootstrap.sh'),'utf8'), daemon=fs.readFileSync(path.join(HERE,'mac-worker-b-daemon.py'),'utf8');
let consumed=false;
// pairConsumed
let pairIssued=false;
let registration=fs.existsSync(REGISTRATION)?JSON.parse(fs.readFileSync(REGISTRATION,'utf8')):null;
const now=()=>new Date().toISOString(), auth=(req,v)=>(req.headers.authorization||'')===`Bearer ${v}`;
function send(res,code,data,headers={}){const out=JSON.stringify(data);res.writeHead(code,{'content-type':'application/json; charset=utf-8','content-length':String(Buffer.byteLength(out)),...headers});res.end(out);}
function atomicWrite(file,value){const tmp=path.join(path.dirname(file),`.${path.basename(file)}.${process.pid}.tmp`);fs.writeFileSync(tmp,JSON.stringify(value,null,2)+'\n',{mode:0o600});fs.renameSync(tmp,file);}
function file(kind,id){return path.join(DIRS[kind],`${id}.json`);} function read(kind,id){try{return JSON.parse(fs.readFileSync(file(kind,id),'utf8'));}catch{return null;}}
function cardFile(id){return path.join(CALL_CARDS,`${id}.json`);} function readCard(id){try{return JSON.parse(fs.readFileSync(cardFile(id),'utf8'));}catch{return null;}}
function bounded(v,n){return String(v??'').slice(0,n);} function cardSummary(task){return bounded(task.task,512);}
function cardForTask(task){return {taskId:task.taskId,state:'queued',taskSummary:cardSummary(task),model:bounded(task.model||'',128),modelLevel:bounded(task.modelLevel||task.reasoningEffort||'default',64),queuedAtUtc:now(),sessionIds:[],usage:null};}
function existsAny(id){return ['queued','processing','results'].some(k=>fs.existsSync(file(k,id)));} async function body(req,limit=MAX_BODY){let n=0,ch=[];for await(const c of req){n+=c.length;if(n>limit)throw Error('body too large');ch.push(c);}return JSON.parse(Buffer.concat(ch).toString('utf8')||'{}');}
function remoteAddress(req){const raw=String(req.socket.remoteAddress||'').replace(/^::ffff:/i,'');return net.isIP(raw)?raw:'';}
function sanitized(x,req,previous=null){return {schema:'spike-home.mac-worker-b.registration.v1',host:String(x.host||'').slice(0,128),platform:String(x.platform||'').slice(0,64),arch:String(x.arch||'').slice(0,32),remoteAddress:remoteAddress(req)||previous?.remoteAddress||'',servicePort:Number.isInteger(Number(x.servicePort))?Number(x.servicePort):0,codexVersion:String(x.codexVersion||'').slice(0,128),nodeVersion:'',capabilities:Array.isArray(x.capabilities)?x.capabilities.map(String).slice(0,32):[],registeredAtUtc:previous?.registeredAtUtc||now(),lastHeartbeatAtUtc:now()};}
function liveRegistration(){if(!registration||!net.isIP(String(registration.remoteAddress||''))||!Number.isInteger(registration.servicePort)||registration.servicePort<1||registration.servicePort>65535)return false;const age=Date.now()-Date.parse(registration.lastHeartbeatAtUtc||'');return Number.isFinite(age)&&age>=0&&age<REGISTRATION_MAX_AGE_MS;}
function counts(){return {queuedCount:fs.readdirSync(DIRS.queued).filter(x=>x.endsWith('.json')).length,processingCount:fs.readdirSync(DIRS.processing).filter(x=>x.endsWith('.json')).length,resultCount:fs.readdirSync(DIRS.results).filter(x=>x.endsWith('.json')).length};} function statusFor(id){return read('results',id)||read('processing',id)||read('queued',id)||read('status',id);}
function validateTask(x){if(!x||typeof x!=='object'||!ID_RE.test(x.taskId||''))throw Error('invalid taskId');if(typeof x.task!=='string'||!x.task||Buffer.byteLength(x.task,'utf8')>MAX_BODY)throw Error('task body invalid or too large');if(x.resumeSessionId!==undefined&&x.resumeSessionId!==null&&(!ID_RE.test(x.resumeSessionId)||typeof x.resumeSessionId!=='string'))throw Error('invalid resumeSessionId');return x;}
function claimNext(){const p=fs.readdirSync(DIRS.processing).filter(x=>x.endsWith('.json')).sort(),q=fs.readdirSync(DIRS.queued).filter(x=>x.endsWith('.json')).sort(),name=p[0]||q[0];if(!name)return null;const id=name.slice(0,-5);if(q.includes(name))fs.renameSync(file('queued',id),file('processing',id));const task=read('processing',id);const card=readCard(id);if(card){atomicWrite(cardFile(id),{...card,state:'running',runningAtUtc:card.runningAtUtc||now()});}return task;}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host}`);
 if(req.method==='GET'&&u.pathname===`/bootstrap/${bootstrapToken}`){if(consumed)return send(res,410,{error:'bootstrap token already used'});consumed=true;const s=template.replaceAll('__BRIDGE_URL__',`http://${lanAddress()}:${PORT}`).replaceAll('__PAIRING_SECRET__',secret).replaceAll('__MAC_PORT__',String(DEFAULT_MAC_PORT)).replace('__DAEMON_B64__',Buffer.from(daemon).toString('base64'));res.writeHead(200,{'content-type':'text/x-shellscript; charset=utf-8','cache-control':'no-store'});return res.end(s);}
 if(req.method==='GET'&&u.pathname===`/pair/${pairToken}`){if(pairIssued)return send(res,410,{error:'pair token already used'},{'cache-control':'no-store'});pairIssued=true;const b=Buffer.from(daemon);return send(res,200,{schema:'spike-home.mac-worker-b.pair.v1',transport:'reverse-pull-v1',bridgeUrl:`http://${lanAddress()}:${PORT}`,workerPort:DEFAULT_MAC_PORT,pairingSecret:secret,workerPyBase64:b.toString('base64'),workerSha256:crypto.createHash('sha256').update(b).digest('hex'),expectedCodexPath:'/Applications/ChatGPT.app/Contents/Resources/codex',expectedPythonPath:'/Library/Frameworks/Python.framework/Versions/3.9/bin/python3',defaultModel:'gpt-5.6-luna',allowedSandboxes:['read-only','workspace-write'],astraDefaultBlocked:true,generatedAtUtc:now()},{'cache-control':'no-store'});}
 if(req.method==='POST'&&(u.pathname==='/register'||u.pathname==='/heartbeat')){if(!auth(req,secret))return send(res,401,{error:'unauthorized'});const x=await body(req);if(u.pathname==='/heartbeat'&&registration&&remoteAddress(req)!==registration.remoteAddress)return send(res,409,{error:'registration peer changed'});registration=sanitized(x,req,registration);atomicWrite(REGISTRATION,registration);return send(res,200,{ok:true});}
 if(req.method==='GET'&&u.pathname==='/worker/next'){if(!auth(req,secret))return send(res,401,{error:'unauthorized'});const task=claimNext();if(!task){res.writeHead(204);return res.end();}return send(res,200,task);}
 if(req.method==='POST'&&u.pathname==='/worker/result'){if(!auth(req,secret))return send(res,401,{error:'unauthorized'});const x=await body(req,MAX_RESULT_BODY);if(!x||typeof x!=='object'||!ID_RE.test(x.taskId||''))return send(res,400,{error:'invalid taskId'});if(fs.existsSync(file('results',x.taskId)))return send(res,200,{ok:true,taskId:x.taskId,state:read('results',x.taskId)?.state||'completed',idempotent:true});if(!fs.existsSync(file('processing',x.taskId)))return send(res,404,{error:'task not processing'});atomicWrite(file('results',x.taskId),x);atomicWrite(file('status',x.taskId),{...x,state:x.state||'completed',completedAtUtc:now()});const card=readCard(x.taskId);if(card){const cardState=x.state==='failed'?'failed':'completed';const update={...card,state:cardState,finishedAtUtc:now(),sessionIds:Array.isArray(x.sessionIds)?x.sessionIds:[],usage:x.usage??null,exitCode:x.exitCode??null,lastMessagePreview:bounded(x.lastMessage??x.lastMessagePreview??x.error??'',512)};for(const k of ['resumeSessionId','resumeMismatch'])if(Object.prototype.hasOwnProperty.call(x,k))update[k]=x[k];atomicWrite(cardFile(x.taskId),update);}fs.rmSync(file('processing',x.taskId),{force:true});return send(res,200,{ok:true,taskId:x.taskId,state:x.state||'completed'});}
 if(u.pathname.startsWith('/api/')){if(!auth(req,taskBearer))return send(res,401,{error:'unauthorized'});if(u.pathname==='/api/status'||u.pathname==='/api/worker/status')return send(res,200,{ok:true,bridge:'running',reversePull:true,...counts(),ready:liveRegistration(),registration});if(u.pathname==='/api/worker/start')return send(res,200,{ok:true,desired:'running',reversePull:true,...counts(),ready:liveRegistration(),registration});if(u.pathname==='/api/worker/stop')return send(res,200,{ok:true,desired:'stopped',note:'stop LaunchAgent on Mac; bridge does not control arbitrary processes'});if(req.method==='POST'&&(u.pathname==='/api/task'||u.pathname==='/api/submit')){const x=validateTask(await body(req));if(existsAny(x.taskId))return send(res,409,{error:'duplicate taskId'});atomicWrite(file('queued',x.taskId),x);atomicWrite(file('status',x.taskId),{...x,state:'queued',queuedAtUtc:now()});atomicWrite(cardFile(x.taskId),cardForTask(x));return send(res,202,{ok:true,taskId:x.taskId,state:'queued'});}if(req.method==='GET'&&u.pathname.startsWith('/api/card/')){const id=decodeURIComponent(u.pathname.slice(10));if(!ID_RE.test(id))return send(res,400,{error:'invalid taskId'});const card=readCard(id);return card?send(res,card.state==='completed'||card.state==='failed'?200:202,card):send(res,404,{error:'not found'});}if(req.method==='GET'&&(u.pathname.startsWith('/api/task/')||u.pathname.startsWith('/api/poll/'))){const prefix=u.pathname.startsWith('/api/poll/')?10:11,id=decodeURIComponent(u.pathname.slice(prefix));if(!ID_RE.test(id))return send(res,400,{error:'invalid taskId'});const value=statusFor(id);if(!value)return send(res,404,{error:'not found'});return send(res,value.state==='completed'||value.state==='failed'?200:202,value);}}
 send(res,404,{error:'not found'});
}catch(e){send(res,e.message==='body too large'?413:400,{error:e.message});}});
function lanAddresses(){const a=[];for(const xs of Object.values(os.networkInterfaces()))for(const x of xs||[])if(x.family==='IPv4'&&!x.internal)a.push(x.address);return [...new Set(a)];}function lanAddress(){return process.env.SPIKE_WORKER_B_LAN_IP||lanAddresses()[0]||'127.0.0.1';}
server.listen(PORT,'0.0.0.0',()=>{console.log(`Spike Worker B bridge listening on ${PORT}`);console.log(`Pair URL: http://${lanAddress()}:${PORT}/pair/${pairToken}`);console.log(`Legacy bootstrap URL: http://${lanAddress()}:${PORT}/bootstrap/${bootstrapToken}`);});
