import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import net from 'node:net';

const root=process.cwd(), state=path.join(root,'.private','mac-worker-b','bridge-fixture-'+Date.now()); fs.mkdirSync(state,{recursive:true});
const probe=net.createServer(); await new Promise(r=>probe.listen(0,'127.0.0.1',r)); const port=probe.address().port; await new Promise(r=>probe.close(r));
const env={...process.env,SPIKE_WORKER_B_PORT:String(port),SPIKE_WORKER_B_LAN_IP:'127.0.0.1',SPIKE_WORKER_B_STATE_DIR:state};
function start(){return spawn(process.execPath,[path.join(root,'bootstrap','mac-worker-b','bridge.mjs')],{env,stdio:['ignore','pipe','pipe']});}
async function waitBridge(p){let out='';p.stdout.on('data',x=>out+=x);await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('bridge timeout')),5000),i=setInterval(()=>{if(out.includes('Pair URL:')){clearTimeout(t);clearInterval(i);resolve();}},20);});const m=out.match(/Pair URL: (http:\/\/[^\s]+)/);const u=new URL(m[1]);return {out,base:`http://127.0.0.1:${u.port}`,pair:m[1]};}
const req=(base,p,opts={})=>fetch(base+p,opts), post=(base,p,x,h)=>req(base,p,{method:'POST',headers:{'content-type':'application/json',...h},body:JSON.stringify(x)});
let bridge, info; try {
 bridge=start(); info=await waitBridge(bridge); const pair=await req(info.base,new URL(info.pair).pathname); assert.equal(pair.status,200); const bundle=await pair.json();
 assert.equal(bundle.transport,'reverse-pull-v1'); assert.equal((await req(info.base,new URL(info.pair).pathname)).status,410);
 const daemon=fs.readFileSync(path.join(root,'bootstrap','mac-worker-b','mac-worker-b-daemon.py')); assert.deepEqual(Buffer.from(bundle.workerPyBase64,'base64'),daemon); assert.equal(bundle.workerSha256,crypto.createHash('sha256').update(daemon).digest('hex'));
 const secret=fs.readFileSync(path.join(state,'pairing.secret'),'utf8').trim(), worker='Bearer '+secret, taskBearer='Bearer '+crypto.createHmac('sha256',secret).update('task-api-v1').digest('hex');
 assert.equal((await req(info.base,'/worker/next',{headers:{authorization:taskBearer}})).status,401); assert.equal((await req(info.base,'/api/status',{headers:{authorization:worker}})).status,401);
 assert.equal((await post(info.base,'/register',{host:'fixture',platform:'darwin',arch:'arm64',servicePort:8767,codexVersion:'fixture',capabilities:['health']},{authorization:worker})).status,200);
 const taskText=('第一行 🚀\n第二行 — 多字节 Unicode\n'.repeat(900)); assert.ok(Buffer.byteLength(taskText)>20*1024); const task={taskId:'unicode-task',task:taskText,targetCwd:root,model:'gpt-5.6-luna',sandbox:'workspace-write'};
  assert.equal((await post(info.base,'/api/submit',{...task,modelLevel:'balanced',reasoningEffort:'ignored'},{authorization:taskBearer})).status,202); assert.ok(fs.existsSync(path.join(state,'call-cards',task.taskId+'.json'))); assert.ok(!fs.existsSync(path.join(state,'reverse','call-cards',task.taskId+'.json'))); let card=await req(info.base,'/api/card/'+task.taskId,{headers:{authorization:taskBearer}}); assert.equal(card.status,202); let cardBody=await card.json(); assert.equal(cardBody.state,'queued'); assert.equal(cardBody.modelLevel,'balanced'); assert.equal(cardBody.sessionIds.length,0); assert.equal(cardBody.usage,null);
 const next=await req(info.base,'/worker/next',{headers:{authorization:worker}}); assert.equal(next.status,200); const pulled=await next.json(); assert.equal(pulled.task,taskText); assert.equal(crypto.createHash('sha256').update(pulled.task,'utf8').digest('hex'),crypto.createHash('sha256').update(taskText,'utf8').digest('hex')); card=await req(info.base,'/api/card/'+task.taskId,{headers:{authorization:taskBearer}}); assert.equal((await card.json()).state,'running');
 const result={schema:'spike-home.mac-worker-b.result.v1',taskId:task.taskId,state:'completed',ok:true,exitCode:0,lastMessage:'fixture result',sessionIds:['sess-1'],usage:{inputTokens:10,cachedInputTokens:4,outputTokens:3,reasoningOutputTokens:1,totalTokens:13}}; assert.equal((await post(info.base,'/worker/result',result,{authorization:worker})).status,200); assert.equal((await post(info.base,'/worker/result',result,{authorization:worker})).status,200);
 card=await req(info.base,'/api/card/'+task.taskId,{headers:{authorization:taskBearer}}); cardBody=await card.json(); assert.equal(cardBody.state,'completed'); assert.deepEqual(cardBody.sessionIds,['sess-1']); assert.equal(cardBody.usage.totalTokens,13); assert.equal(cardBody.lastMessagePreview,'fixture result');
 const polled=await req(info.base,'/api/poll/'+task.taskId,{headers:{authorization:taskBearer}}); assert.equal(polled.status,200); assert.equal((await polled.json()).lastMessage,'fixture result'); assert.equal((await post(info.base,'/api/submit',task,{authorization:taskBearer})).status,409);
 const failedTask={...task,taskId:'failed-card',task:'failed'}; assert.equal((await post(info.base,'/api/submit',failedTask,{authorization:taskBearer})).status,202); assert.equal((await req(info.base,'/worker/next',{headers:{authorization:worker}})).status,200); assert.equal((await post(info.base,'/worker/result',{taskId:failedTask.taskId,state:'failed',ok:false,exitCode:7,error:'bad resume',resumeSessionId:'sess-1',resumeMismatch:true},{authorization:worker})).status,200); card=await req(info.base,'/api/card/'+failedTask.taskId,{headers:{authorization:taskBearer}}); cardBody=await card.json(); assert.equal(cardBody.state,'failed'); assert.equal(cardBody.resumeMismatch,true); assert.equal(cardBody.exitCode,7);
 const restartTask={...task,taskId:'redeliver-task',task:'restart me'}; assert.equal((await post(info.base,'/api/submit',restartTask,{authorization:taskBearer})).status,202); assert.equal((await req(info.base,'/worker/next',{headers:{authorization:worker}})).status,200); bridge.kill(); await new Promise(r=>bridge.once('exit',r)); bridge=start(); info=await waitBridge(bridge); assert.equal((await req(info.base,'/worker/next',{headers:{authorization:worker}})).status,200);
  const status=await req(info.base,'/api/status',{headers:{authorization:taskBearer}}); const facts=await status.json(); assert.equal(facts.reversePull,true); assert.equal(facts.processingCount,1); assert.equal(facts.resultCount,2); assert.equal(facts.ready,true);
 console.log('PASS reverse-pull submit -> next -> result -> poll; no Mac listener; Unicode byte preservation; duplicate task/result; processing redelivery after bridge restart; auth separation; pair bytes/hash');
} finally {if(bridge&&!bridge.killed)bridge.kill();fs.rmSync(state,{recursive:true,force:true});}
