import test from 'node:test';
import assert from 'node:assert/strict';
import os from 'node:os';import fs from 'node:fs';import path from 'node:path';
import {CodexAgentExecutor} from '../../state/safe-boot/seed-lkg/codexless-runtime/src/codex-agent-executor.mjs';
import {LazyCodexAgentExecutor} from '../../state/safe-boot/seed-lkg/codexless-runtime/src/lazy-codex-agent-executor.mjs';
import {RuntimeOperator} from '../../state/safe-boot/seed-lkg/codexless-runtime/src/operator-control.mjs';
import {UsageLedger} from '../../state/safe-boot/seed-lkg/codexless-runtime/src/operator-usage.mjs';
const usage=(i,o)=>({inputTokens:i,cachedInputTokens:0,outputTokens:o,reasoningOutputTokens:0,totalTokens:i+o});
function factory(root){let notify=null;let active=true;const turns=[];const client={get running(){return active;},initializedResult:{ok:true},async start(){return this.initializedResult;},onNotification(cb){notify=cb;return()=>{notify=null;};},async request(method){if(method==='thread/start')return {thread:{id:'test-thread'},model:'test-model'};if(method==='turn/start'){const turn={id:'turn-'+(turns.length+1),status:'inProgress',items:[]};turns.unshift(turn);return {turn};}if(method==='thread/turns/list')return {data:turns};if(method==='thread/resume')return {thread:{id:'test-thread',canAcceptDirectInput:true},model:'test-model'};throw new Error('unexpected '+method);},async close(){active=false;}};return {executor:new CodexAgentExecutor({defaultCwd:root,clientFactory:()=>client}),emit(total,turnId=turns[0].id){notify({method:'thread/tokenUsage/updated',params:{threadId:'test-thread',turnId,tokenUsage:{total,last:usage(1,1)}}});},finish(){turns[0].status='completed';notify({method:'turn/completed',params:{threadId:'test-thread',turn:turns[0]}});},get turn(){return turns[0];}};}
test('actual executor notifications record every turn independent of panel and reject stale usage',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'spike-usage-executor-'));const f=factory(root),op=new RuntimeOperator({root});op.attachCodex('codex-b',f.executor);await op.listen();await f.executor.open();try{const a=await f.executor.start({task:'first',clientRequestId:'one'});f.emit(usage(100,20));f.emit(usage(200,40));f.finish();const first=f.turn.id;let report=op.usageLedger.report();assert.equal(report.summary.totalTokens,240);await f.executor.send({agentRef:a.agentRef,message:'second',clientRequestId:'two'});f.emit(usage(300,60),first);assert.equal(f.executor.operatorSnapshot()[0].usage,null);f.emit(usage(300,60));f.finish();report=op.usageLedger.report();assert.equal(report.summary.totalTokens,360);assert.equal(report.summary.recordedTurns,2);assert.equal(report.records.find(r=>r.turnId!==first).usage.totalTokens,120);assert.ok(report.records.every(r=>r.runtimePid===process.pid));}finally{await op.close();await f.executor.close();fs.rmSync(root,{recursive:true,force:true});}});
test('observer failures never block execution and lazy runtime propagates observer',async()=>{const f=factory(process.cwd()),rows=[];const lazy=new LazyCodexAgentExecutor({factory:async()=>f.executor});lazy.setOperatorObserver(r=>{rows.push(r);throw new Error('test recording unavailable');});try{const s=await lazy.start({task:'no paid model',clientRequestId:'observation'});f.emit(usage(20,10));f.finish();assert.ok(rows.length>=3);assert.equal((await lazy.show({agentRef:s.agentRef})).status,'idle');assert.equal(f.executor.operatorTelemetryError,'test recording unavailable');}finally{await lazy.close();}});


test('native non-Codex task results record real per-task usage without an open panel',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'spike-usage-provider-')),op=new RuntimeOperator({root});const rows=[{ref:'z-1',status:'completed',startedAt:Date.now()-200,finishedAt:Date.now(),model:'glm-test',workspace:root,usage:{inputTokens:30,outputTokens:10,totalTokens:40}}];const adapter={async start(){return rows[0];},async send(){return rows[0];},async status(){return rows[0];},listJobs(){return rows;}};op.attachProvider('zcode',adapter);await op.listen();try{await op.refreshForeign();await op.refreshForeign();const r=op.usageLedger.report();assert.equal(r.summary.totalTokens,40);assert.equal(r.summary.recordedTurns,1);assert.equal(r.records[0].project,root);}finally{await op.close();fs.rmSync(root,{recursive:true,force:true});}});
