import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {UsageLedger,normalizeUsage,usageDelta,zeroUsage,historyObservations} from '../../state/safe-boot/seed-lkg/codexless-runtime/src/operator-usage.mjs';
import {createPanel,operatorPolicy} from '../server.mjs';
const NOW=Date.now();
const cleanupTasks=new WeakMap();
function cleanup(t,fn){cleanupTasks.get(t).push(fn);}
function root(t){const p=fs.mkdtempSync(path.join(os.tmpdir(),'spike-usage-test-'));cleanupTasks.set(t,[]);t.after(async()=>{for(const close of cleanupTasks.get(t).reverse())await close();fs.rmSync(p,{recursive:true,force:true});});return p;}
const counts=(input,output,cached=0,reasoning=0)=>({inputTokens:input,outputTokens:output,cachedInputTokens:cached,reasoningOutputTokens:reasoning,totalTokens:input+output});
const observation=(extra={})=>({provider:'codex-b',ref:'agent-test',turnId:'turn-one',model:'model-one',status:'completed',startedAt:NOW-1000,updatedAt:NOW,endedAt:NOW,usage:{total:counts(100,20,50,5),last:counts(10,2)},usageBaseline:zeroUsage(),...extra});
function ledger(t,p=root(t),options={}){const l=new UsageLedger({root:p,now:()=>NOW,...options});cleanup(t,()=>l.close());return l;}
test('token subcomponents never inflate total and missing metrics remain unknown',()=>{const x=normalizeUsage(counts(100,20,60,4));assert.equal(x.totalTokens,120);assert.equal(normalizeUsage({}).totalTokens,null);assert.equal(normalizeUsage({inputTokens:100,outputTokens:20}).totalTokens,120);assert.equal(normalizeUsage({inputTokens:10,cachedInputTokens:20}).cachedInputTokens,null);});
test('turn deltas subtract a real baseline and never use latest response as full task',()=>{assert.equal(usageDelta(counts(200,40),counts(100,20)).totalTokens,120);assert.equal(usageDelta(counts(200,40),null).totalTokens,null);assert.equal(usageDelta(counts(80,20),counts(100,20)).totalTokens,null);});
test('repeated observation, history refresh, and account isolation do not duplicate usage',t=>{const l=ledger(t);for(let i=0;i<20;i++)l.record(observation());let r=l.report();assert.equal(r.summary.recordedTurns,1);assert.equal(r.summary.totalTokens,120);l.record(observation({provider:'codex-a'}));r=l.report();assert.equal(r.summary.totalTokens,240);assert.equal(r.summary.recordedTurns,2);assert.equal(l.report({provider:'codex-b'}).summary.totalTokens,120);assert.equal(l.report({model:'unknown'}).summary.recordedTurns,0);});
test('continuation uses cumulative delta rather than double-counting thread totals',t=>{const l=ledger(t);l.record(observation());l.record(observation({turnId:'turn-two',startedAt:NOW-400,usage:{total:counts(250,50),last:counts(30,2)},usageBaseline:counts(100,20)}));assert.equal(l.report().summary.totalTokens,300);assert.equal(l.report().summary.knownTurns,2);});
test('out-of-order or incomplete observations cannot erase a known receipt',t=>{const l=ledger(t);l.record(observation());l.record(observation({updatedAt:NOW-500,usage:{total:counts(10,1)}}));l.record(observation({updatedAt:NOW+1,usage:null,status:'running',endedAt:null}));const r=l.report().records[0];assert.equal(r.usage.totalTokens,120);assert.equal(r.status,'completed');});
test('last-response-only rows are visible but not silently counted as zero/full usage',t=>{const l=ledger(t);l.record(observation({usage:{last:counts(80,20)},usageBaseline:null}));const r=l.report();assert.equal(r.summary.unknownTurns,1);assert.equal(r.summary.knownTurns,0);assert.equal(r.summary.totalTokens,null);assert.equal(r.records[0].latestResponseUsage.totalTokens,100);assert.ok(r.coverage.notes.length>0);});
test('database survives reopening and candidate recording uses a separate database',t=>{const p=root(t);let a=new UsageLedger({root:p,now:()=>NOW});a.record(observation());a.close();a=new UsageLedger({root:p,now:()=>NOW});assert.equal(a.report().summary.totalTokens,120);a.close();const b=ledger(t,p,{port:7691});assert.equal(b.report().summary.recordedTurns,0);});
test('history import deduplicates a replay and allocates continuation by predecessor receipt',t=>{const p=root(t),file=path.join(p,'state/agents/codex-b/agent-task-cards.json');fs.mkdirSync(path.dirname(file),{recursive:true});const one={agentRef:'a',turnId:'t1',action:'start',updatedAt:NOW-300,taskCard:{title:'任务',modelSelection:{selectedModel:'m'}},terminalSnapshot:{status:'completed',timing:{startedAt:NOW-900,endedAt:NOW-500},resourceReceipt:{tokenUsage:{threadTotal:counts(100,20),turn:counts(10,1)}}}};const two={...one,turnId:'t2',action:'send',updatedAt:NOW-1,terminalSnapshot:{status:'completed',timing:{startedAt:NOW-200,endedAt:NOW-10},resourceReceipt:{tokenUsage:{threadTotal:counts(180,30),turn:counts(11,1)}}}};fs.writeFileSync(file,JSON.stringify({records:[one,two,one]}));const l=ledger(t,p);l.ingestHistory({force:true});l.ingestHistory({force:true});assert.equal(l.report().summary.recordedTurns,2);assert.equal(l.report().summary.totalTokens,210);assert.equal(historyObservations(p).rows[1].usage.totalTokens,90);});
test('filter parameters are bounded; strings never become executable SQL',t=>{const l=ledger(t);l.record(observation());assert.throws(()=>l.report({days:0}));assert.throws(()=>l.report({days:10000}));assert.throws(()=>l.report({provider:'other'}));assert.equal(l.report({model:"' OR 1=1 --"}).summary.recordedTurns,0);assert.throws(()=>l.report({limit:90000}));});
test('source metadata cannot promote an API caller to system administrator',()=>{const p=operatorPolicy();assert.equal(p.canOverrideAgentPreferences,true);assert.equal(p.physicalPresenceVerified,false);assert.ok(p.effectiveSource.includes('硬边界'));});
test('usage endpoint is authenticated, read-only and reports coverage and pagination',async t=>{const p=root(t);const l=new UsageLedger({root:p});l.record(observation());l.close();const runtime=async()=>({counts:{active:0,awaitingApproval:0,starting:0,uncertain:0},tasks:[],providers:[],commands:{},memory:null});const app=createPanel({root:p,port:19732,runtime,bridgeHealth:async()=>({healthy:true,ok:true,pid:process.pid,version:'test',toolCount:50}),tunnel:async(_,lane)=>({lane,connected:true}),systemAction:async()=>({tasks:{}}),startWatchdog:false});await app.start();cleanup(t,()=>app.close());const base='http://127.0.0.1:19732';assert.equal((await fetch(base+'/api/usage')).status,401);assert.equal((await fetch(base+'/api/usage',{headers:{'x-panel-token':app.token,origin:'https://foreign.invalid'}})).status,403);const r=await fetch(base+'/api/usage?days=7',{headers:{'x-panel-token':app.token}});assert.equal(r.status,200);const v=await r.json();assert.equal(v.summary.totalTokens,120);assert.equal(v.pagination.total,1);assert.equal((await fetch(base+'/api/usage',{method:'POST',headers:{'x-panel-token':app.token}})).status,404);});


test('provider task receipts import exact ZCode totals including cache and reasoning aliases',t=>{const p=root(t),file=path.join(p,'state/agents/zcode/jobs.json');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify({records:[{ref:'z-1',model:'glm-test',status:'completed',startedAt:NOW-900,finishedAt:NOW-10,usage:{inputTokens:100,outputTokens:20,totalTokens:120,cacheReadTokens:50,reasoningTokens:3}},{ref:'z-2',model:'glm-test',status:'interrupted',startedAt:NOW-600,finishedAt:NOW-1,usage:null}]}));const l=ledger(t,p);l.ingestHistory({force:true});l.ingestHistory({force:true});const r=l.report({provider:'zcode'});assert.equal(r.summary.recordedTurns,2);assert.equal(r.summary.totalTokens,120);assert.equal(r.summary.cachedInputTokens,50);assert.equal(r.summary.reasoningOutputTokens,3);assert.equal(r.summary.unknownTurns,1);});
