// One reviewed integration transaction. No glob rewriting, no rollback of other work.
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const base='state/safe-boot/seed-lkg/codexless-runtime/src/';
const changes=new Map();
function edit(p,from,to,n=1){let r=changes.get(p);if(!r){const before=fs.readFileSync(path.join(root,p),'utf8');r={before,after:before};changes.set(p,r);}const count=r.after.split(from).length-1;if(count!==n)throw new Error(p+': expected '+n+' matching anchors, found '+count);r.after=r.after.split(from).join(to);}
edit("state/safe-boot/seed-lkg/codexless-runtime/src/codex-agent-executor.mjs","  async listModels({","  operatorSnapshot() {\n    return [...this.#agents.values()].map(state => ({\n      ref: state.agentRef, requestId: state.operatorRequestId ?? null,\n      cwd: state.cwd, turnId: state.currentTurnId, status: state.status,\n      model: state.resolvedModel ?? state.requestedModel,\n      effort: state.reasoningEffort ?? state.requestedReasoningEffort,\n      startedAt: state.turnStartedAt ?? state.createdAt, updatedAt: state.updatedAt,\n      endedAt: state.turnEndedAt, pendingApproval: state.pendingApproval ? structuredClone(state.pendingApproval) : null,\n      result: typeof state.finalResult === \"string\" ? state.finalResult.slice(0,16000) : null,\n      error: state.latestError, usage: state.latestTokenUsage ? structuredClone(state.latestTokenUsage) : null,\n    }));\n  }\n\n  async listModels({",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/codex-agent-executor.mjs","      agentRef,\n      cwd: effectiveCwd,","      agentRef,\n      operatorRequestId: clientRequestId,\n      cwd: effectiveCwd,",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/lazy-codex-agent-executor.mjs","  async listModels(input)","  operatorSnapshot() { return this.#delegate?.operatorSnapshot?.() ?? []; }\n\n  async listModels(input)",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/codexless-runtime.mjs","export async function createCodexlessRuntime({","import { RuntimeOperator } from \"./operator-control.mjs\";\n\nexport async function createCodexlessRuntime({",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/codexless-runtime.mjs","  let agentExecutor = null;","  const operatorControl = new RuntimeOperator({ root: bridgeRoot, port: Number(env.CODEX_TOOLBOX_PUBLIC_PORT || 7690), memory: experienceMemory });\n  let agentExecutor = null;",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/codexless-runtime.mjs","    // HTTP MCP serving in SDK 2.x constructs a fresh McpServer per request.","    operatorControl.attachCodex(\"codex-a\", agentExecutor);\n    operatorControl.attachCodex(\"codex-b\", codexBExecutor);\n    operatorControl.attachProvider(\"zcode\", agentProviderRegistry.get(\"zcode\"));\n    operatorControl.attachProvider(\"mac\", agentProviderRegistry.get(\"mac\"));\n\n    // HTTP MCP serving in SDK 2.x constructs a fresh McpServer per request.",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/codexless-runtime.mjs","      codexAgentRouter,\n      maxConcurrent,","      codexAgentRouter,\n      operatorControl,\n      maxConcurrent,",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/codexless-runtime.mjs","      closed = true;\n      try {","      closed = true;\n      await operatorControl.close();\n      try {",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/codexless-runtime.mjs","      createServer,\n      close,","      createServer,\n      operator: operatorControl,\n      operatorHandlers: agentToolHandlerSink,\n      close,",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/mcp-server-factory.mjs","export function createCommandConcurrencyGate({ maxConcurrent = 2, resolveWriterProjectKey = null } = {})","export function createCommandConcurrencyGate({ maxConcurrent = 2, resolveWriterProjectKey = null, getMaxConcurrent = null } = {})",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/mcp-server-factory.mjs","      if (inFlight >= maxConcurrent) {","      const limit = getMaxConcurrent ? getMaxConcurrent() : maxConcurrent;\n      if (!Number.isInteger(limit) || limit < 1 || limit > 4) throw new Error(\"invalid dynamic command concurrency limit\");\n      if (inFlight >= limit) {",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/mcp-server-factory.mjs","message: `bridge concurrency limit reached (${maxConcurrent})`,","message: `bridge concurrency limit reached (${limit})`,",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/mcp-server-factory.mjs","  codexAgentRouter = null,\n}) {","  codexAgentRouter = null,\n  operatorControl = null,\n}) {",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/mcp-server-factory.mjs","  const commandConcurrency = createCommandConcurrencyGate({ maxConcurrent, resolveWriterProjectKey });","  const commandConcurrency = createCommandConcurrencyGate({ maxConcurrent, resolveWriterProjectKey, getMaxConcurrent: operatorControl ? () => operatorControl.commandLimit() : null });\n  if (operatorControl) operatorControl.commandGate = commandConcurrency;",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/mcp-server-factory.mjs","        if (toolHandlerSink && typeof args[handlerIndex] === \"function\") {","        if (operatorControl && typeof args[handlerIndex] === \"function\") args[handlerIndex] = operatorControl.wrapTool(name, args[handlerIndex]);\n        if (toolHandlerSink && typeof args[handlerIndex] === \"function\") {",1);
edit("plugins/housekeeping/index.mjs","  async function start() {","  async function start({ runOnStart = true } = {}) {",1);
edit("plugins/housekeeping/index.mjs","    void runOnce({ reason: \"startup\" });","    if (runOnStart) void runOnce({ reason: \"startup\" });",1);
edit("runtime/codexless/mcp-http-with-git-commit-and-spike-context.mjs","        housekeeping: housekeeping.status(),","        housekeeping: housekeeping.status(),\n        operator: runtime.operator ? { version: 1, ...runtime.operator.health() } : null,",1);
edit("runtime/codexless/mcp-http-with-git-commit-and-spike-context.mjs","await housekeeping.start();","// Register the exact existing handlers once for the private management pipe.\ncreateServer();\nawait runtime.operator?.listen({ handlers: runtime.operatorHandlers, housekeeping });\nawait housekeeping.start();",1);
edit("runtime/codexless/mcp-http-with-git-commit-and-spike-context.mjs","    housekeeping.stop();","    await runtime.operator?.close();\n    housekeeping.stop();",1);
edit("runtime/safe-boot/spike-home-production.g3.mjs","import { SafeBootStore }","import { withOperatorMaintenance } from \"./operator-maintenance.mjs\";\nimport { SafeBootStore }",1);
edit("runtime/safe-boot/spike-home-production.g3.mjs","\"adopt-lkg\", \"ensure\", \"status\"]","\"adopt-lkg\", \"ensure\", \"status\", \"restart\"]",1);
edit("runtime/safe-boot/spike-home-production.g3.mjs","async function freezeCurrent(options={}) { const source=","async function freezeCurrent(options={}) {\n  if(process.env.SPIKE_BRIDGE_REVIEWED_SOURCE){\n    const reviewed=path.join(STATE_ROOT,\"work\",\"operator-reviewed-source\");\n    if(path.resolve(process.env.SPIKE_BRIDGE_REVIEWED_SOURCE)!==reviewed)fail(\"reviewed candidate source path is not allowed\");\n    return freeze(reviewed,options);\n  }\n  const source=",1);
edit("runtime/safe-boot/spike-home-production.g3.mjs","async function status(){","async function restartStable(){\n  return withLock(async()=>{\n    const state=await store.readState();if(!state.lastKnownGood||state.pending)fail(\"stable restart requires an idle verified LKG\");\n    const release=releaseFromRecord(state.lastKnownGood);release.manifest=await verifyIntegrity(release.path);\n    const pf=await preflight(release.path);if(!pf.passed)fail(\"stable restart preflight failed\");\n    const old=await productionIdentity(),h=await health(7690);\n    if(!old||!h.ok||h.healthz?.body?.artifactDigest!==release.manifest.digest)fail(\"stable restart identity mismatch; use ensure for recovery\");\n    const session=randomUUID();await event(session,\"operator_restart_started\",{pid:old.pid,digest:release.manifest.digest});\n    await stopExact(old.pid,7690);\n    const pid=await startRelease(release,7690,session),next=await waitHealth(7690,release.manifest.digest,pid);\n    await writeManagedBridgeRecord(release,pid,session,next);await event(session,\"operator_restart_completed\",{pid,digest:release.manifest.digest});\n    return {result:\"PASS\",action:\"restart\",oldPid:old.pid,pid,digest:release.manifest.digest};\n  });\n}\nasync function status(){",1);
edit("runtime/safe-boot/spike-home-production.g3.mjs","case\"promote\":return promote();","case\"promote\":return withOperatorMaintenance(ROOT,()=>promote(),{allowLegacy:process.env.SPIKE_OPERATOR_BOOTSTRAP===\"1\"});case\"restart\":return withOperatorMaintenance(ROOT,()=>restartStable());",1);
edit("RUN-TUNNEL-ACCOUNT-A-TASK.ps1","$proxy = 'http://127.0.0.1:7890'","$proxy = 'http://127.0.0.1:7890'\n$operatorSettings=Join-Path $root 'config\\operator.json'\nif(Test-Path -LiteralPath $operatorSettings){\n  $operatorConfig=Get-Content -Raw -LiteralPath $operatorSettings|ConvertFrom-Json\n  if($null -ne $operatorConfig.tunnels.a.proxyUrl){\n    $proxy=[string]$operatorConfig.tunnels.a.proxyUrl\n    if($proxy){\n      $proxyUri=[Uri]$proxy\n      if($proxyUri.Scheme -notin @('http','https') -or $proxyUri.UserInfo -or $proxyUri.Query -or $proxyUri.Fragment -or $proxyUri.AbsolutePath -ne '/'){throw '控制台代理地址格式无效。'}\n    }\n  }\n}",1);
edit("RUN-TUNNEL-ACCOUNT-B-TASK.ps1","$proxy = 'http://127.0.0.1:7890'","$proxy = 'http://127.0.0.1:7890'\n$operatorSettings=Join-Path $root 'config\\operator.json'\nif(Test-Path -LiteralPath $operatorSettings){\n  $operatorConfig=Get-Content -Raw -LiteralPath $operatorSettings|ConvertFrom-Json\n  if($null -ne $operatorConfig.tunnels.b.proxyUrl){\n    $proxy=[string]$operatorConfig.tunnels.b.proxyUrl\n    if($proxy){\n      $proxyUri=[Uri]$proxy\n      if($proxyUri.Scheme -notin @('http','https') -or $proxyUri.UserInfo -or $proxyUri.Query -or $proxyUri.Fragment -or $proxyUri.AbsolutePath -ne '/'){throw '控制台代理地址格式无效。'}\n    }\n  }\n}",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/package.json","\"version\": \"0.1.2-preview.10\"","\"version\": \"0.1.2-preview.11\"",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/package-lock.json","\"version\": \"0.1.2-preview.10\"","\"version\": \"0.1.2-preview.11\"",2);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/surface-contracts.mjs","export const PUBLIC_SERVER_VERSION = \"0.1.2-preview.10\"","export const PUBLIC_SERVER_VERSION = \"0.1.2-preview.11\"",1);
edit("state/safe-boot/seed-lkg/codexless-runtime/src/surface-contracts.mjs","+model-quota-filter-v1\"","+model-quota-filter-v1+operator-control-v1\"",1);

const manifest=[];
for(const [file,r] of changes){
  if(fs.readFileSync(path.join(root,file),'utf8')!==r.before)throw new Error('Concurrent change: '+file);
  manifest.push({file,beforeHash:createHash('sha256').update(r.before).digest('hex'),afterHash:createHash('sha256').update(r.after).digest('hex')});
}
if(process.argv.includes('--apply')){
  const backup=path.join(root,'state','operator','integration-backup');fs.mkdirSync(backup,{recursive:true});
  for(const [file,r] of changes){const b=path.join(backup,file);fs.mkdirSync(path.dirname(b),{recursive:true});if(!fs.existsSync(b))fs.writeFileSync(b,r.before);}
  for(const [file,r] of changes){if(fs.readFileSync(path.join(root,file),'utf8')!==r.before)throw new Error('Concurrent change: '+file);fs.writeFileSync(path.join(root,file),r.after);}
  fs.writeFileSync(path.join(backup,'manifest.json'),JSON.stringify(manifest,null,2));
}
console.log(JSON.stringify({result:'PASS',applied:process.argv.includes('--apply'),files:manifest},null,2));
